### PR TITLE
Change speaker layout to fix iPhone Safari rendering

### LINKED ISSUE #20: Speaker images are laid out wrong in Safari on iPhone
IMG_0280

### PR DESCRIPTION
**Pull request by mkretz**
Fixes #20 

Nesting `grid` within a `flex-column` or `flex` seems to be a problem on iPhone Safari. With this slightly altered layout for the speakers, we could avoid the issue.

### CODE REVIEW

File: src/routes/Speakers.svelte [hunk 1]
```diff
@@ -37,17 +37,16 @@
...
-					<a href="/speakers/{speaker.slug}">
-						<Avatar src={speaker.imgSrc} width="w-48" height="h-48" class="mb-4" />
-					</a>
-					<h4>{speaker.name}</h4>
-					<p>{speaker.company}</p>
-				</div>
-			{/each}
-		</div>
+	</div>
+	<div class="grid md:grid-cols-3 gap-16">
```
Comment (cloudlena) [inline src/routes/Speakers.svelte]: Moving the speakers outside the `#speakers` div doesn't work, as now they spread wider than the rest of the content of the website. I think, we have to find a different solution. @mkretz, should we check together tomorrow?

**Review by cloudlena — CHANGES_REQUESTED** [review]

**Review by cloudlena — APPROVED** [review]
